### ISSUE TITLE
Publshing blade components and views in a separate directory

### ISSUE THREAD

**Issue by XarchencoMO** [laravel/jetstream#1377] opened 2023-09-18 18:02 UTC
when i publishing your blade and livewire components or views, they are published in default directories (views and views/components), But if I already have my own blade components or views with the same name, they just are overwritten by yours, if you will be publishing them to another directory (views/jetstream and (views/jetstream/components or views/components/jetstream)), then this will not happen

**Comment by jessarcher** [comment] 2023-09-19 00:57
Duplicate of #1364.

> Jetstream is a scaffold tool which is only intended for new Laravel applications. Using it on existing applications can lead to overwritten code like you're experiencing. Please see the Jetstream docs: https://jetstream.laravel.com/installation.html
> <img alt="Screenshot 2023-08-22 at 08 49 47" width="852" src="https://user-images.githubusercontent.com/594614/262259135-501ba01f-9426-4c22-bb57-b90dd7020337.png">

I've explained the reasoning for not using a `jetstream` directory in the comments of #1364.

**Closed by jessarcher** 2023-09-19 00:57 UTC
