### ISSUE TITLE
"Interface "Psr\Cache\CacheItemInterface" not found" on laravel new

### ISSUE THREAD

**Issue by kayden1940** [laravel/jetstream#1552] opened 2024-12-10 03:25 UTC
### Jetstream Version

5.3

### Jetstream Stack

Inertia

### Laravel Version

11.31

### PHP Version

8.2

### Database Driver & Version

Mysql for mac 8.0.33

### Description

I am trying to start jetstream with "laravel new" and the profile it's not working.

### Steps To Reproduce

Starting jetstream with "laravel new", get into the logged in profile page causing "Interface "Psr\Cache\CacheItemInterface" not found"

**Comment by crynobone** [comment] 2024-12-10 03:29
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by kayden1940** [comment] 2024-12-10 03:48
> Hey there, thanks for reporting this issue.
> 
> We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue _as one separate commit_ on the main/master branch and share the repository here?
> 
> Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.
> 
> ```
> laravel new bug-report --github="--public"
> ```
> 
> Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.
> 
> Thanks!

here:
https://github.com/kayden1940/1552-reproduce
This is literally the vanilla setup and all dependencies are newly installed. Boot up DBngin, register and go to profile would see the error.

**Comment by crynobone** [comment] 2024-12-10 07:36
This seems to be an issue with `mobiledetect/mobiledetectlib`. PR submitted https://github.com/serbanghita/Mobile-Detect/pull/975

For the time being you can solve this by running the following command:

```shell
composer require "psr/cache"
```

**Comment by crynobone** [comment] 2024-12-10 08:08
Fixed via latest `mobiledetect/mobiledetectlib`

**Closed as completed by crynobone** 2024-12-10 08:08 UTC
Labels: bug
