### ISSUE TITLE
Totp is enabled without verification

### ISSUE THREAD

**Issue by waffshappen** [laravel/jetstream#429] opened 2020-11-03 11:21 UTC
- Jetstream Version: 1.5.3
- Jetstream Stack: Livewire
- Laravel Version:8.12.3
- PHP Version:  7.4
- Database Driver & Version: sqlite, but not relevant

### Description:
When enabling TOTP in the jetstream settings it will only show a qr code and recovery code and immediately enable it.
This can be dangerous for the user as they could instantly loose access on errors or on forgetting to scan the code and getting logged out.

Almost every other application asks for atleast one successful totp entry in the flow to make sure the user not only understands what totp is and how to use it, but also to ensure that it was not done on accident and is saved on the target device the user had in mind. This also ensures the target totp handler actually works as intended.

TOTP is also missing a field/button to show the totp secret directly so it can be saved on desktop clients like KeepassXC without first having to go through a RFID scanner, then copying it by hand as a major inconvenience.

### Steps To Reproduce:
Enable TOTP on the settings page.
Observe no field for confirmation of TOTP.
Observe no button to show the TOTP for copying it into a desktop client (KeepassXC)

**Comment by driesvints** [comment] 2020-11-03 11:40
Duplicate of https://github.com/laravel/jetstream/issues/74

**Closed by driesvints** 2020-11-03 11:40 UTC
