### ISSUE TITLE
Livewire V3 have been released, So I'm appreciated if you guys should support V3 of livewire

### ISSUE THREAD

**Issue by Gmk0** [laravel/jetstream#1354] opened 2023-08-09 20:07 UTC

**Comment by Devsome** [comment] 2023-08-09 23:53
@Gmk0 I think it will be started when Livewire 3 is out of beta so no duplicate work is done.

**Comment by crynobone** [comment] 2023-08-10 00:24
Duplicate of #1348

**Closed** 2023-08-10 00:24 UTC

**Comment by incon** [comment] 2023-08-10 03:27
It would be nice to have a beta version to use, just like how Filament is doing a beta version for V3.
