### ISSUE TITLE
[Windows] Wrong Vite manifest when creating a Laravel project with Jetstream (css path with incorrect backslash)

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [laravel/jetstream#1098] opened 2022-07-21 14:39 UTC
- Jetstream Version: 2.10.1
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.21.4
- PHP Version: 8.1.0
- Database Driver & Version: Mysql 8

### Description:

When creating a new Laravel project with Jetstream on Windows machines, after running **npm run build** to compile the Vite assets, the **public\build\manifest.json** is being generated with wrong backslashes in the CSS path, as you can see in the following image, and causing the following exception:

```
Unable to locate file in Vite manifest
```

![image](https://user-images.githubusercontent.com/11933789/180235783-d8f2e884-3ba5-47b2-a4c5-cbfcf84c0d78.png)

The issue was confirmed on Windows 11 and Windows 10 machines. It was also tested on a Linux machine with Ubuntu 20.04, but the problem doesn't happen.

It started happening this week, as projects created until last week were correctly generating the manifest.json file.

> The issue doesn't happens when creating a new Laravel project without Jetstream

### Steps To Reproduce:

1 - Create a new Laravel project with Jetstream/Livewire (maybe using **laravel new project --jet**) on a Windows machine
2 - Run **npm run build** to compile the Vite assets
3 - Open the file **public\build\manifest.json** to see the backslashes

### Related Issues

https://github.com/TiagoSilvaPereira/vemto-issues/issues/351
https://github.com/laravel/vite-plugin/issues/19

**Comment by timacdonald** [comment] 2022-07-21 23:27
Duplicate of: https://github.com/laravel/vite-plugin/issues/101 We can continue the conversation over there.

**Closed by timacdonald** 2022-07-21 23:27 UTC

**Comment by LeviCanales** [comment] 2022-07-22 23:25
composer create-project laravel/laravel myproject --no-cache
cd myproject
composer require laravel/jetstream -W --no-cache
php artisan jetstream:install livewire
npm install
npm run build
php artisan migrate
same bug with slash in app.css
