### ISSUE TITLE
Image Save button has to be pressed twice to save image

### ISSUE THREAD

**Issue by NanoCellWebDesign** [laravel/jetstream#234] opened 2020-09-19 02:38 UTC
- Jetstream Version: 1.2.1
- Jetstream Stack: Livewire
- Laravel Version: 8.5.0
- PHP Version: 7.4.6
- Database Driver & Version: 10.3.24-MariaDB

### Description:

To save a profile image you have to press the save button twice. the first press saves the image to `storage\app\livewire-tmp`. The second press saves the image to `storage\public\profile-photos` and saves to the database.

[See Video Here](https://youtu.be/g3AhCKXtwL4)

### Steps To Reproduce:

(Watch the storage folder on separate screen or side of screen while performing the following)

Upload new profile image

Press save button

Image goes into tmp folder but not into profile folder and db not updated

Press save again

Image now goes into tmp folder and into profile folder + db is updated + page refreshes

**Comment by alxmtr** [comment] 2020-09-19 15:10
I haven't been able to reproduce. 

On a fresh install of Jetstream with Livewire everything works fine for me. 
After selecting the image, it is saved to `storage\app\livewire-tmp` and pressing the save button saves the image to `storage\app\public\profile-photos` correctly. 

Removing the photo works fine as well.

**Comment by NanoCellWebDesign** [comment] 2020-09-20 12:52
> I haven't been able to reproduce.
> 
> On a fresh install of Jetstream with Livewire everything works fine for me.
> After selecting the image, it is saved to `storage\app\livewire-tmp` and pressing the save button saves the image to `storage\app\public\profile-photos` correctly.
> 
> Removing the photo works fine as well.

Any idea what this could be, this is on a fresh install i am running on as well?

**Comment by alxmtr** [comment] 2020-09-20 14:07
@NanoCellWebDesign what is your operating system?

**Comment by NanoCellWebDesign** [comment] 2020-09-20 14:13
@alxmtr Win 10

**Comment by alxmtr** [comment] 2020-09-20 14:18
@NanoCellWebDesign Did you have a look at the requests on your browser devtools?

**Comment by NanoCellWebDesign** [comment] 2020-09-20 19:49
@alxmtr yes I believe I know why this happens now.

The upload to temp is happening as soon as you select a photo but if you press save quickly after then the image will not be saved and only stored in temp due to requests still running. if I have dev tools open and wait until requests stop then press save, it seems to work correctly.

This don't seem too user friendly as they have know what of telling when the image has finished uploading.

Maybe we need a progress bar or to have the save button disabled until all the requests have finished?

**Comment by driesvints** [comment] 2020-09-21 12:34
Think it's indeed probably best to disable the button until the temp upload has finished.

**Comment by driesvints** [comment] 2020-09-21 15:41
Tbvh. I haven't been able to reproduce this and this is the only report we've gotten so far. I'm going to close this as this doesn't seems like an issue to happen frequently. If you can dig into a fix we're appreciating prs. Thanks.

**Closed by driesvints** 2020-09-21 15:41 UTC
Labels: bug

**Comment by alturic** [comment] 2020-09-23 02:27
Sorry for reopening this, but I'm running my dev install in a Docker container (locally, but still) and this same problem happens to me. I don't know how to confirm this per see, but it's definitely due to the file still uploading when hitting save. The preview shows instantly, but it's still uploading in the backend.

**Comment by alxmtr** [comment] 2020-09-23 11:44
To @NanoCellWebDesign and @alturic 

If you are using Windows 10 with WSL 2 and put your files on the mounted Windows file system, this might be the reason your requests are slow. In this case, using Docker probably makes it even slower. WSL 2 is much faster when your files are directly on the Linux file system.

**Comment by NanoCellWebDesign** [comment] 2020-09-23 11:55
It is more of an issue when on a dev env with slow requests obviously but i still think disabling the button while the fike is being uploaded will fix the issue.

It would atleast show the use that something is happening.

Will try make a fix tonight

**Comment by alturic** [comment] 2020-09-24 01:41
@alxmtr Nope, just straight-up Docker over Hyper-V with shared folders mounted. It still does come back around to a slow request, whether that is disk or someone on cell service.

**Comment by zzkevinlim** [comment] 2022-01-07 06:55
This bug is still here.

**Comment by inpresif** [comment] 2024-03-30 12:51
4 years later, I have the same (thanks for the hint so I can stop looking why/where the image went) issue.

Fresh install of: Laravel 11
Windows 11
Docker setup

Local setup.

![image](https://github.com/laravel/jetstream/assets/12870992/144f2776-c358-43bf-8389-3487632f468f)
