### ISSUE TITLE
Opt in dark mode support is actually not opt in

### ISSUE THREAD

**Issue by ziming** [laravel/jetstream#1226] opened 2023-01-18 13:18 UTC
- Jetstream Version: 2.15
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 9.48
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 8

### Description:

I originally commented in with screenshots proof. But thought i should create an issue instead as that is a closed PR and it is likely nobody sees it

https://github.com/laravel/jetstream/pull/1209#issuecomment-1386977200

But tldr, I installed jetstream months ago, composer update this morning and tonight my jetstream sites all look very weird with some components dark and some components white.

So it looks like it is actually not opt in as I never ran the jetstream:install --dark command since my installation of Jetstream is months ago, not today.

All I did is a composer update, nothing else.

**Comment by RhysLees** [comment] 2023-01-18 15:18
This was fixed here: https://github.com/laravel/jetstream/pull/1224

**Comment by ziming** [comment] 2023-01-18 16:02
I hope so. release is not tagged yet. will find out later if it did indeed fix the issue or not.

**Comment by jessarcher** [comment] 2023-01-18 22:46
> This was fixed here: #1224

That won't fix this particular issue. The problem is that existing users of the Livewire stack often won't have published views. After updating, they'll now be using views with dark classes.

> @ziming you should first publish your components as recommended on the [docs](https://jetstream.laravel.com/2.x/installation.html#livewire), then you can update.

This is correct, but I don't think it's something people will know about or should have to do.

At this stage, the only solution I can think of is to revert the dark mode changes.

We could then either:

1. Push them forward to a major release and mention it in the upgrade guide, or
2. Keep the original "legacy" views in the packages resources directory and put the dark mode versions in the stubs directory, and always publish them on new installs to avoid problems like this going forward.

**Comment by jessarcher** [comment] 2023-01-18 23:04
Hey @ziming, we've reverted the dark mode changes for now. The issue should be resolved when you update to Jetstream `2.16.0`.

**Closed by jessarcher** 2023-01-18 23:04 UTC
